### ISSUE TITLE
Scaling Nether database fails identity model authentication

### ISSUE THREAD

**Issue by navalev** [MicrosoftDX/nether#413]
#111
steps to reproduce:
1. Scale the nether database (assume this will happen on a restart with no scaling as well).
2. Issue an API call (get players, get leaderboard...)
3. Resolved with server side restart

Error:
```
2017-03-19 19:04:34.105 +00:00 [Information] Failed to validate the token "eyJhbGciOiJSUzI1NiIsImtpZCI6ImJlNjBiYzI1ZTZiNGRkMGViYzhkMjU4ZGViMmFhOTczIiwidHlwIjoiSldUIn0.eyJuYmYiOjE0ODk5NDY2ODIsImV4cCI6MTQ4OTk1MDI4MiwiaXNzIjoiaHR0cHM6Ly9uZXRoZXJsb2FkLmF6dXJld2Vic2l0ZXMubmV0L2lkZW50aXR5IiwiYXVkIjpbImh0dHBzOi8vbmV0aGVybG9hZC5henVyZXdlYnNpdGVzLm5ldC9pZGVudGl0eS9yZXNvdXJjZXMiLCJuZXRoZXItYWxsIl0sImNsaWVudF9pZCI6InJlc291cmNlb3duZXJ0ZXN0Iiwic3ViIjoiNTJkZDdmZjAtY2FjNy00ZjZlLTg3OGYtZGRjODU2MzNkZjhiIiwiYXV0aF90aW1lIjoxNDg5OTQ2NjgyLCJpZHAiOiJsb2NhbCIsIm5hbWUiOiI1MmRkN2ZmMC1jYWM3LTRmNmUtODc4Zi1kZGM4NTYzM2RmOGIiLCJyb2xlIjoiQWRtaW4iLCJzY29wZSI6WyJuZXRoZXItYWxsIl0sImFtciI6WyJwYXNzd29yZCJdfQ.YVkY1OA8LmK5uoLJQEP_tunR8K1KHzokoPYO_LFQIvAvZJMXiaBD4ugkf2hEem4c49wbyOdWih_6vMi_BQuCD1J0c0z3IqwhNCbKdEgtljaXWztALnMEsK_3jlv2StXgCB0mW-gphSWave_PKp9gqJMQhJNRF5I7ddT3E1MLzhewSqgYhEK0EYNplpGcHN9n2wSDSEeJOynuEYNE2_PMqTLcoi5KVH-RPk_l77Gtz9bXP07N1_AKdAOXp-5ls-fRNMMK66m3k1UFzT36l_nFj1zUBo00qUzm4gHd4FcgoCHL9oNO_kZIIeukPiIK-kDFzrlCksIgr_FLzjL37m92ig".
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match 'kid': 'be60bc25e6b4dd0ebc8d258deb2aa973', 
token: '{"alg":"RS256","typ":"JWT","kid":"be60bc25e6b4dd0ebc8d258deb2aa973"}.{"nbf":1489946682,"exp":1489950282,"iss":"https://netherload.azurewebsites.net/identity","aud":["https://netherload.azurewebsites.net/identity/resources","nether-all"],"client_id":"resourceownertest","sub":"52dd7ff0-cac7-4f6e-878f-ddc85633df8b","auth_time":1489946682,"idp":"local","name":"52dd7ff0-cac7-4f6e-878f-ddc85633df8b","role":"Admin","scope":["nether-all"],"amr":["password"]}'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()
2017-03-19 19:04:34.105 +00:00 [Information] "Bearer" was not authenticated. Failure message: "IDX10501: Signature validation failed. Unable to match 'kid': 'be60bc25e6b4dd0ebc8d258deb2aa973', 
token: '{\"alg\":\"RS256\",\"typ\":\"JWT\",\"kid\":\"be60bc25e6b4dd0ebc8d258deb2aa973\"}.{\"nbf\":1489946682,\"exp\":1489950282,\"iss\":\"https://netherload.azurewebsites.net/identity\",\"aud\":[\"https://netherload.azurewebsites.net/identity/resources\",\"nether-all\"],\"client_id\":\"resourceownertest\",\"sub\":\"52dd7ff0-cac7-4f6e-878f-ddc85633df8b\",\"auth_time\":1489946682,\"idp\":\"local\",\"name\":\"52dd7ff0-cac7-4f6e-878f-ddc85633df8b\",\"role\":\"Admin\",\"scope\":[\"nether-all\"],\"amr\":[\"password\"]}'."
2017-03-19 19:04:34.339 +00:00 [Information] Authorization failed for user: null.
2017-03-19 19:04:34.339 +00:00 [Information] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'.
```

**Comment by stuartleeks** [comment]
@navalev which client was this using? had you previously authenticated prior to the database scaling?

**Comment by navalev** [comment]
Used Admin UI which was logged in and authenticated prior to the scaling.

**Comment by stuartleeks** [comment]
Ok. Did you log out or refresh the browser at any point in the steps you described?

**Comment by navalev** [comment]
no - was able to run the APIs successfully only after server side restart.

**Comment by stuartleeks** [comment]
Were there any errors in the logs prior to restarting?
